// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsbHlFAIc8DzpftuytDaUci9vjNNMuLnk',
    appId: '1:126897816814:web:968d9d09f6b8aaf2c41fff',
    messagingSenderId: '126897816814',
    projectId: 'remoteaccess-af2f1',
    authDomain: 'remoteaccess-af2f1.firebaseapp.com',
    databaseURL: 'https://remoteaccess-af2f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'remoteaccess-af2f1.appspot.com',
    measurementId: 'G-J0VYVX3705',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU--B2Jc3Wj942IojApdmxqXvSgmrBZN4',
    appId: '1:126897816814:android:9705938145b8d0dcc41fff',
    messagingSenderId: '126897816814',
    projectId: 'remoteaccess-af2f1',
    databaseURL: 'https://remoteaccess-af2f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'remoteaccess-af2f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT5BalA0GoJEB4rbmcMojwrLJFQ4lJSmc',
    appId: '1:126897816814:ios:0eceddca052a448cc41fff',
    messagingSenderId: '126897816814',
    projectId: 'remoteaccess-af2f1',
    databaseURL: 'https://remoteaccess-af2f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'remoteaccess-af2f1.appspot.com',
    iosClientId: '126897816814-748bsfcdm73g0rpk3i83tbc8b5dig221.apps.googleusercontent.com',
    iosBundleId: 'com.redsandev.firebaseMockup',
  );
}
